Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2022-11, with the labels that each got.

#730 Docs: new section in the /diffuser page
  source/locales/pages/en-us/diffuser.md
  source/locales/pages/fr/diffuser.md
Labels: documentation, Inciter au partage, i18n, ITN5, t9n

#737 fix(t9n): 'I do not know' -> 'I don't know'
  source/locales/ui/ui-en-us.yaml
Labels: ITN5, t9n

#741 feat(ui): new LangSwitcher design
  source/components/LangSwitcher.tsx
  source/components/Logo.tsx
  source/components/SessionBar.tsx
  source/components/TranslationAlertBanner.tsx
  source/sites/publicodes/App.tsx
  source/sites/publicodes/Landing.tsx
Labels: graphique 🎨, UX, i18n, ITN5, t9n

#743 Different wording for contribution pages
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
  source/sites/publicodes/Contribution.js
  source/sites/publicodes/TranslationContribution.tsx
Labels: tech, Inciter au partage, ITN5, t9n

#744 fix(t9n): add missing whitspaces in the StatsContent translation content
  source/components/stats/StatsContent.js
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
Labels: bug, t9n

#745 Make MarkdownPage Meta optional; fix #742 no desc meta on landing
  source/sites/publicodes/LandingExplanations.tsx
  source/sites/publicodes/pages/MarkdownPage.tsx
Labels: bug, tech
