Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2022-10, with the labels that each got.

#671 nettoyage et gros bug localisation -> "chargement du moteur"
  source/RulesProvider.js
  source/components/localisation/Localisation.tsx
  source/components/localisation/supportedCountries.yaml
  source/components/localisation/useLocalisation.ts
  source/components/useBranchData.ts
  source/reducers/rootReducer.ts
  source/sites/publicodes/LandingExplanations.tsx
Labels: bug

#679 fix(dependency): d3-color vulnerable to ReDoS
  .nvmrc
  package.json
  yarn.lock
Labels: bug, dependencies

#375 Améliorations des cartes action
  source/components/Stamp.tsx
  source/sites/publicodes/ActionVignette.js
  source/sites/publicodes/ActionsChosenIndicator.tsx
  source/sites/publicodes/ActionsOptionsBar.tsx
  source/sites/publicodes/AllActions.tsx
Labels: peu prioritaire, graphique 🎨

#692 fix(stats): to calculate score, end pages need to have a details param
  source/components/stats/content/ScoreFromURL.js
Labels: bug
