Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2022-09, with the labels that each got.

#570 Iconographie
  source/components/SafeCategoryImage.tsx
  source/components/SessionBar.tsx
  source/components/conversation/AnswerList.tsx
  source/components/conversation/CategoryRespiration.js
  source/images/climate-change-small.svg
  source/images/climate-change-small.variations.svg
  source/images/model/alimentation . boisson.svg
  source/images/model/alimentation . déchets.svg
  source/images/model/alimentation . déjeuner et dîner.svg
  source/images/model/alimentation . gaspillage alimentaire.svg
  source/images/model/alimentation . petit déjeuner annuel.svg
  source/images/model/alimentation . repas.svg
  source/images/model/alimentation.svg
  source/images/model/divers . autres produits (copie).svg
  source/images/model/divers . textile.svg
  source/images/model/divers . électroménager.svg
  source/images/model/divers.svg
  source/images/model/logement . chauffage.svg
  source/images/model/logement . construction.svg
  source/images/model/logement . électricité.svg
  source/images/model/logement.svg
  source/images/model/maison.svg
  source/images/model/numérique . TV.svg
  source/images/model/numérique . internet.svg
  source/images/model/numérique . ordinateur fixe.svg
  source/images/model/numérique . ordinateur portable.svg
  source/images/model/numérique . tablette.svg
  source/images/model/numérique . téléphone.svg
  source/images/model/numérique.svg
  source/images/model/services publics.svg
  source/images/model/transport . avion.svg
  source/images/model/transport . bus.svg
  source/images/model/transport . deux roues thermique.svg
  source/images/model/transport . train.svg
  source/images/model/transport . voiture . empreinte.svg
  source/images/model/transport.svg
  source/images/silhouette.svg
  source/images/three-dots.svg
  source/sites/publicodes/CategoryVisualisation.tsx
  source/sites/publicodes/Landing.js
  source/sites/publicodes/Personas.tsx
  source/sites/publicodes/chart/Bar.js
  source/sites/publicodes/chart/RavijenChart.tsx
  source/sites/publicodes/chart/SquaresGrid.tsx
  source/sites/publicodes/chart/SubCategoryBar.tsx
  source/sites/publicodes/fin/Catégories.tsx
  source/sites/publicodes/fin/ClimateTargetChart.tsx
Labels: graphique 🎨

#635 Feat: amélioration de l'animation de fin
  source/sites/publicodes/chart/RavijenChart.tsx
  source/types/companyTypes.ts
Labels: UX

#640 logo png
  index.html
  source/components/Logo.tsx
  source/images/favicon.png
  source/images/logo.png
  source/images/petit-logo.png
  source/images/petit-logo@2x.png
  source/images/petit-logo@3x.png
  source/sites/publicodes/App.tsx
  source/sites/publicodes/Logo.js
  source/sites/publicodes/LogoComponent.tsx
  source/sites/publicodes/Navigation.tsx
Labels: nouveauté, graphique 🎨

#629 Amélioration pour lighthouse
  index.html
  source/RulesProvider.js
  source/actions/existingCompanyActions.ts
  source/components/ProgressCircle.tsx
  source/components/SessionBar.tsx
  source/components/conversation/Conversation.tsx
  source/components/conversation/RuleInput.tsx
  source/components/conversation/select/SearchAirports.js
  source/components/conversation/select/SelectCommune.tsx
  source/components/conversation/select/SelectEuropeCountry.tsx
  source/components/conversation/select/SelectTauxRisque.js
  source/components/conversation/select/SelectTauxRisque.worker.js
  source/components/conversation/select/airports.csv
  source/components/emoji.js
  source/components/ui/Fonts.css
  source/components/utils/EngineContext.tsx
  source/images/nosgestesclimat.png
  source/images/nosgestesclimat.webp
  source/reducers/rootReducer.ts
  source/sites/publicodes/App.tsx
  source/sites/publicodes/Landing.js
  source/sites/publicodes/Profil.tsx
  source/sites/publicodes/Tutorial.tsx
  source/sites/publicodes/chart/SubCategoriesChart.tsx
  source/sites/publicodes/sitemap.txt
Labels: SEO

#645 Textes sur la page d'accueil pour le SEO
  package.json
  scripts/fetch-releases.js
  source/components/AnimatedIllustration.tsx
  source/components/IllustrationSVG.tsx
  source/components/NewsBanner.tsx
  source/components/ui/Typography.css
  source/images/ecolab-climat-dessin.clipped-test.svg
  source/images/illustration.svg
  source/images/marianne.svg
  source/images/play-triangle-orange.svg
  source/sites/publicodes/App.tsx
  source/sites/publicodes/Landing.js
  source/sites/publicodes/LandingContent.tsx
  source/sites/publicodes/LandingExplanations.tsx
  source/sites/publicodes/avantages.yaml
  source/sites/publicodes/landing.md
  yarn.lock
Labels: SEO

#626 Localisation 2
  README.md
  netlify.toml
  netlify/edge-functions/geolocation.ts
  package.json
  source/RulesProvider.js
  source/actions/actions.ts
  source/components/SessionBar.tsx
  source/components/SlidesLayout.tsx
  source/components/localisation/Localisation.tsx
  source/components/localisation/LocalisationMessage.tsx
  source/components/localisation/frenchCountryPrepositions.yaml
  source/components/localisation/supportedCountries.yaml
  source/components/localisation/useLocalisation.ts
  source/components/ui/IllustratedMessage.tsx
  source/components/useBranchData.ts
  source/components/utils/NewTabSvg.tsx
  source/reducers/rootReducer.ts
  source/selectors/storageSelectors.ts
  source/sites/publicodes/App.tsx
  source/sites/publicodes/FAQ.yaml
  source/sites/publicodes/Profil.tsx
  source/storage/persistSimulation.ts
  yarn.lock
Labels: i18n, ITN5
