Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2023-07, with the labels that each got.

#1067 Refactor(types/imports): towards more exhaustive type annotations
  package.json
  source/Provider.tsx
  source/RulesProvider.tsx
  source/actions/actions.ts
  source/components/Feedback/Northstar.tsx
  source/components/Feedback/NorthstarBanner.tsx
  source/components/Notifications.tsx
  source/components/SearchBar.tsx
  source/components/SessionBar.tsx
  source/components/conversation/Aide.tsx
  source/components/conversation/AnswerList.tsx
  source/components/conversation/Conversation.tsx
  source/components/conversation/Explicable.tsx
  source/components/conversation/RuleInput.tsx
  source/components/conversation/estimationQuestions.tsx
  source/components/localisation/utils.ts
  source/components/publicodesUtils.tsx
  source/components/ui/Checklist/index.css
  source/components/ui/Checklist/index.tsx
  source/components/utils/EngineContext.tsx
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
  source/reducers/rootReducer.ts
  source/reducers/storageReducer.ts
  source/selectors/simulationSelectors.ts
  source/selectors/storageSelectors.ts
  source/sites/publicodes/Action.tsx
  source/sites/publicodes/ActionVignette.tsx
  source/sites/publicodes/App.tsx
  source/sites/publicodes/CategoryVisualisation.tsx
  source/sites/publicodes/Simulateur.tsx
  source/sites/publicodes/SimulationList.tsx
  source/sites/publicodes/chart/RavijenChart.tsx
  source/sites/publicodes/chart/SubCategoriesChart.tsx
  source/sites/publicodes/chart/chartUtils.ts
  source/sites/publicodes/enquête/Banner.tsx
  source/sites/publicodes/enquête/Enquête.tsx
  source/sites/publicodes/enquête/ReturnToEnquêteButton.tsx
  source/sites/publicodes/enquête/SendResultButton.tsx
  source/sites/publicodes/enquête/enquêteSelector.ts
  source/sites/publicodes/pages/Documentation.tsx
  source/sites/publicodes/pages/Plan.tsx
  source/storage/persistEverything.ts
  source/storage/persistSimulation.ts
  source/utils.ts
  yarn.lock
Labels: tech

#1205 Fix: sitemap script generation + update sitemap.txt
  scripts/generateSitemap.ts
  source/sites/publicodes/sitemap.txt
Labels: bug, tech, SEO

#1180 Fix releases
  scripts/i18n/translate-release.js
  source/locales/releases/releases-en-us.json
  source/locales/releases/releases-fr.json
Labels: bug, t9n

#1178 Fix: go to specific question only if the test is completed
  cypress/e2e/test-completion/questions-order.cy.js
  cypress/e2e/test-completion/url-redirection.cy.js
  cypress/e2e/test-completion/utils.js
  scripts/generateSitemap.ts
  source/actions/actions.ts
  source/components/Simulation.tsx
  source/components/conversation/CategoryRespiration.tsx
  source/components/conversation/Conversation.tsx
  source/components/conversation/MosaicInputSuggestions.tsx
  source/components/conversation/RuleInput.tsx
  source/components/conversation/SimulationEnding.tsx
  source/components/conversation/conversationUtils.ts
  source/components/conversation/select/SelectDevices.tsx
  source/components/publicodesUtils.tsx
  source/components/utils/EngineContext.tsx
  source/hooks/useNextQuestion.tsx
  source/reducers/rootReducer.ts
  source/selectors/simulationSelectors.ts
  source/sites/publicodes/ActionConversation.tsx
  source/sites/publicodes/ActionPlus.js
  source/sites/publicodes/BandeauContribuer.js
  source/sites/publicodes/Simulateur.tsx
  source/sites/publicodes/chart/InlineCategoryChart.tsx
  source/sites/publicodes/chart/SpecializedVisualisation.tsx
  source/sites/publicodes/tutorial/Tutorial.tsx
  source/utils.ts
Labels: bug

#1247 Fix: padding
  source/global.css
  source/sites/publicodes/App.tsx
Labels: bug

#1251 Fix bug setting personas
  source/components/publicodesUtils.tsx
  source/components/utils/EngineContext.tsx
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
  source/pages/groupe-dashboard/hooks/useGetGroupStats.ts
  source/sites/publicodes/Personas.tsx
  source/sites/publicodes/Simulateur.tsx
Labels: bug
