Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2023-03, with the labels that each got.

#673 Proposition maj texte homepage
  source/locales/pages/fr/landing.md
Labels: documentation

#849 Page stats cassée
  source/components/stats/StatsContent.js
  source/components/stats/content/IframeFigures.js
  source/components/stats/content/ScoreFromURL.js
  source/components/stats/content/sources/Table.js
  source/components/stats/matomo.js
  source/locales/pages/fr/about.md
  source/sites/publicodes/conference/useDatabase.tsx
Labels: bug

#781 fix(t9n): better en-US translation
  package.json
  source/locales/rules-en.yaml
  source/locales/ui/ui-en-us.yaml
  source/sites/publicodes/fin/Petrogaz.tsx
  yarn.lock
Labels: ITN5, t9n

#881 fix css nav bar media quries
  source/components/SessionBar.tsx
  source/sites/publicodes/Landing.tsx
  source/sites/publicodes/ScoreBar.tsx
Labels: UI

#855 New mosaic layout
  source/components/SessionBar.tsx
  source/components/Stamp.tsx
  source/components/conversation/select/NumberedMosaic.tsx
  source/components/conversation/select/SelectDevices.tsx
  source/components/conversation/select/UI.js
  source/components/ui/index.css
Labels: graphique 🎨, UX
