Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2023-04, with the labels that each got.

#917 fix: hot-reloading up and running
  source/components/Footer.tsx
  source/components/conversation/Aide.tsx
  source/components/conversation/Question.tsx
  source/locales/releases/releases-fr.json
  source/sites/publicodes/App.tsx
  source/sites/publicodes/chart/InlineCategoryChart.tsx
  source/sites/publicodes/utils.tsx
Labels: bug

#921 Retire les référence aux projets non pertinentes dans README
  README.md
Labels: documentation

#946 feat(ui): colorize selected country flag in the profil
  source/RulesProvider.tsx
  source/components/localisation/RegionGrid.tsx
  source/components/localisation/useCurrentRegionCode.ts
  source/components/localisation/utils.ts
Labels: UI

#919 Remanie le bouton `Aide au remplissage`
  package.json
  source/components/conversation/Input.tsx
  source/components/conversation/InputSuggestions.tsx
  source/components/conversation/estimate/AnswerTrajetsTable.js
  source/components/conversation/estimate/KmEstimation.tsx
  source/components/conversation/estimate/KmHelp.tsx
  source/components/conversation/estimate/KmHelp/EditableRow.js
  source/components/conversation/estimate/KmHelp/KmForm.js
  source/components/conversation/estimate/KmHelp/KmHelp.css
  source/components/conversation/estimate/KmHelp/KmHelpButton.js
  source/components/conversation/estimate/KmHelp/KmInput.tsx
  source/components/conversation/estimate/KmHelp/ReadOnlyRow.js
  source/components/conversation/estimate/KmHelp/dataHelp.js
  source/components/conversation/estimate/KmHelp/index.tsx
  source/components/conversation/estimate/KmHelpButton.js
  source/components/ui/index.css
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-es.yaml
  source/locales/ui/ui-fr.yaml
  source/sites/publicodes/pages/Simulateurs/ÉconomieCollaborative/StoreContext.tsx
Labels: graphique 🎨, UI

#928 Feat: re-enable the hot-reloading when working on the model
  README.md
  package.json
  source/RulesProvider.tsx
  source/components/localisation/LocalisationProvider.tsx
  source/components/useFetchDocumentation.ts
  source/sites/publicodes/Personas.tsx
  webpack.dev.js
  yarn.lock
Labels: tech

#964 fix(build): markdown loading in dev mode working
  package.json
  source/sites/publicodes/LandingExplanations.tsx
  source/sites/publicodes/pages/About.tsx
  source/sites/publicodes/pages/Accessibility.tsx
  source/sites/publicodes/pages/CGU.tsx
  source/sites/publicodes/pages/Diffuser.tsx
  source/sites/publicodes/pages/DocumentationContexte.tsx
  source/sites/publicodes/pages/Méthode.tsx
  source/sites/publicodes/pages/PetrogazLanding.tsx
  source/sites/publicodes/pages/Privacy.tsx
  webpack.common.js
  webpack.dev.js
  yarn.lock
Labels: bug, tech

#970 fix(components): handle cases where rule aren't sum in extractCategories
  source/components/publicodesUtils.js
Labels: bug

#972 feat(i18n): display region model authors
  source/components/localisation/Localisation.tsx
  source/components/localisation/RegionGrid.tsx
  source/components/localisation/RegionModelAuthors.tsx
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
Labels: i18n, UI

#980 Feat parallelize cypress e2e
  .github/workflows/test-e2e.yaml
  .gitignore
  README.md
  cypress.config.js
  cypress/e2e/integration/about.cy.js
  cypress/e2e/integration/accessibilite.cy.js
  cypress/e2e/integration/group.cy.js
  cypress/e2e/integration/homepage.cy.js
  cypress/e2e/integration/news.cy.js
  cypress/e2e/integration/personas.cy.js
  cypress/e2e/test-completion/default.cy.js
  cypress/e2e/test-completion/test_completion.cy.js
  cypress/e2e/test-completion/utils.js
  cypress/scripts/generateSpecsFromPersonas.js
  dist/_redirects
  dist/demo-iframe.html
  docs/Contributing.md
  docs/_Sidebar.md
  package.json
  source/sites/publicodes/Personas.tsx
Labels: tech

#973 feat: setup Sentry
  package.json
  source/sites/publicodes/entry.js
  yarn.lock
Labels: tech

#940 🎨 Style point info
  source/components/conversation/Explicable.tsx
  source/components/conversation/Question.tsx
  source/images/info.svg
Labels: graphique 🎨
