Repository incubateur-ademe/nosgestesclimat-site, pull requests merged in 2023-02, with the labels that each got.

#835 🐛 Traduction manquante qui empêche l'ouverture de la sous-catégorie "Voiture" depuis la page "Mon profil"
  source/components/conversation/estimate/AnswerTrajetsTable.js
Labels: bug

#838 Fix UI trad and navbar overflow
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
  source/sites/publicodes/Navigation.tsx
Labels: bug, t9n

#804 i18n généralisée, côté site
  package.json
  source/RulesProvider.tsx
  source/components/SessionBar.tsx
  source/components/localisation/Localisation.tsx
  source/components/localisation/LocalisationMessage.tsx
  source/components/localisation/LocalisationProvider.tsx
  source/components/localisation/supportedCountries.yaml
  source/components/localisation/useLocalisation.ts
  source/components/localisation/utils.ts
  source/locales/ui/ui-en-us.yaml
  source/locales/ui/ui-fr.yaml
  source/reducers/rootReducer.ts
  source/sites/publicodes/BandeauContribuer.js
  source/sites/publicodes/Simulateur.js
  yarn.lock
Labels: i18n

#839 Feat: activation de l'optimisation du modèle avec publiopti
  README.md
  package.json
  source/RulesProvider.tsx
  source/reducers/rootReducer.ts
  source/sites/publicodes/pages/QuickDocumentationPage.tsx
  yarn.lock
Labels: tech, publicodes, nouveauté
